/**
 * Audio smoke check: the unit tests drive fakes, so this proves the real thing
 * in a real browser — the context unlocks on a gesture, the ambient graph is
 * running, mute reaches the master gain, and a song dropped into public/songs/
 * is discovered by the manifest and actually plays.
 *
 * Generates its own WAV so the run needs no committed audio (and cleans it up).
 *
 *   node tools/audio-check.mjs [url]
 */
import { chromium } from 'playwright';
import { writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const url = process.argv[2] ?? 'http://localhost:5174';
const songsDir = join(process.cwd(), 'public', 'songs');
const probeSong = join(songsDir, 'audio-check-tone.wav');

/** A 2-second 220 Hz sine as a 16-bit mono WAV. */
function writeToneWav(path) {
  const rate = 8000;
  const samples = rate * 2;
  const buffer = Buffer.alloc(44 + samples * 2);
  buffer.write('RIFF', 0);
  buffer.writeUInt32LE(36 + samples * 2, 4);
  buffer.write('WAVEfmt ', 8);
  buffer.writeUInt32LE(16, 16);
  buffer.writeUInt16LE(1, 20);
  buffer.writeUInt16LE(1, 22);
  buffer.writeUInt32LE(rate, 24);
  buffer.writeUInt32LE(rate * 2, 28);
  buffer.writeUInt16LE(2, 32);
  buffer.writeUInt16LE(16, 34);
  buffer.write('data', 36);
  buffer.writeUInt32LE(samples * 2, 40);
  for (let i = 0; i < samples; i++) {
    buffer.writeInt16LE(Math.round(Math.sin((i / rate) * 220 * 2 * Math.PI) * 12000), 44 + i * 2);
  }
  writeFileSync(path, buffer);
}

const results = [];
const check = (name, pass, detail = '') => {
  results.push({ name, pass, detail });
  console.log(`${pass ? 'PASS' : 'FAIL'}  ${name}${detail ? ` — ${detail}` : ''}`);
};

mkdirSync(songsDir, { recursive: true });
writeToneWav(probeSong);

const browser = await chromium.launch({
  args: ['--autoplay-policy=no-user-gesture-required', '--use-gl=angle'],
});
const page = await browser.newPage();
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));

try {
  await page.goto(url, { waitUntil: 'domcontentloaded' });
  await page.waitForTimeout(2500);

  // The manifest is generated by the vite plugin, not committed.
  const manifest = await page.evaluate(async () => {
    const response = await fetch('/songs/manifest.json');
    return response.ok ? await response.json() : null;
  });
  check(
    'songs manifest lists the dropped-in file',
    !!manifest?.files?.includes('audio-check-tone.wav'),
    JSON.stringify(manifest),
  );

  // Start a game so the full audio wiring (not just the menu) is live.
  const newGame = page.getByRole('button', { name: /new game/i });
  if (await newGame.count()) {
    await newGame.first().click();
    await page.waitForTimeout(4000);
  }

  // A real click is the gesture that unlocks WebAudio.
  await page.mouse.click(640, 300);
  await page.waitForTimeout(600);

  const engine = await page.evaluate(() => {
    const runtime = window.__slimcity?.audio;
    if (!runtime) return { missing: true };
    const ctx = runtime.engine.context();
    return {
      unlocked: runtime.engine.unlocked,
      state: ctx?.state ?? null,
      tracks: runtime.music.state().tracks.map((t) => t.title),
    };
  });
  check('audio runtime is exposed for verification', !engine.missing);
  check('context unlocked by the click gesture', engine.unlocked === true);
  check('context is running, not suspended', engine.state === 'running', String(engine.state));
  check(
    'player picked up the song from public/songs/',
    engine.tracks?.includes('audio-check-tone'),
    JSON.stringify(engine.tracks),
  );

  // Idempotency, in the real app: rescanning must not duplicate.
  const afterRescans = await page.evaluate(async () => {
    const music = window.__slimcity.audio.music;
    await music.scan();
    await music.scan();
    return music.state().tracks.length;
  });
  check('two more rescans do not duplicate tracks', afterRescans === engine.tracks.length, `${afterRescans}`);

  // Actually play it.
  const playback = await page.evaluate(async () => {
    const music = window.__slimcity.audio.music;
    music.play(0);
    await new Promise((r) => setTimeout(r, 1500));
    const state = music.state();
    return { playing: state.playing, time: state.currentTime, error: state.error };
  });
  check(
    'the track plays and the clock advances',
    playback.playing && playback.time > 0,
    JSON.stringify(playback),
  );

  // Mute must reach the master gain.
  const muted = await page.evaluate(() => {
    const engine = window.__slimcity.audio.engine;
    engine.setMasterVolume(0.8, true);
    const value = engine.masterGainValue();
    engine.setMasterVolume(0.8, false);
    return { muted: value, restored: engine.masterGainValue() };
  });
  check(
    'mute zeroes the master gain and unmute restores it',
    muted.muted === 0 && Math.abs(muted.restored - 0.8) < 1e-6,
    JSON.stringify(muted),
  );
} finally {
  await browser.close();
  if (existsSync(probeSong)) rmSync(probeSong);
}

const failed = results.filter((r) => !r.pass);
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
process.exit(failed.length === 0 ? 0 : 1);
